import React from 'react';
import {useParams, Redirect} from 'react-router-dom';

import {confirmationDialog} from "../common/confirms";
import Button from 'react-bootstrap/Button'
import Spinner from 'react-bootstrap/Spinner'
import Row from 'react-bootstrap/Row'
import "regenerator-runtime/runtime";

function EulaSigningCeremony() {
	const [sending, setSending] = React.useState(false);

	const sign_eula = async () => {
		setSending(true);

		const result = await fetch("/api/v1/me/sign_eula", {
			credentials: "same-origin",
			method: "POST"
		});

		if (!result.ok) {
			// TODO: make me less awful
			alert("Failed to sign EULA");
			setSending(false);
			return;
		}

		// Send the user back to the main page.
		document.location.pathname = "/";
	};

	const delete_account = async () => {
		if (!await confirmationDialog(<p>Are you sure?</p>)) {
			return;
		}

		setSending(true);

		const result = await fetch("/api/v1/me", {
			credentials: "same-origin",
			method: "DELETE"
		});

		if (!result.ok) {
			// TODO: make me less awful
			alert("Failed to delete account");
			setSending(false);
			return;
		}

		// Send the user back to the main page.
		document.location.pathname = "/login";
	};

	return <>
			<h1>Disclaimers &amp; Warnings</h1>
				<p>Yes, I'm aware you probably weren't expecting to see this from <i>us</i> of all people, but there are important security implications you should be aware of if 
					you want to use the <code>nffu</code> form-filling service.</p>
			<hr />
				<b>By agreeing to these terms and using the service, you give us permission to:</b>
			<ul>
				<li><b>Store your TDSB username and password:</b> In order to fill in the forms we need to (automatically) log in as your TDSB Google account (since the forms are
					almost entirely set as only accessible to TDSB accounts, and most teachers use the built-in email logging anyways for determining who filled in the form) and to
					do this we must store your password. We cannot use the normal "authorize this app" (OAuth) system because there is no official API for filling in Google Forms automatically.
					We store the passwords encrypted with AES-GCM-256 on our own servers using a key that was generated randomly and that we haven't looked at; however it is technically feasible for us (and anyone
					who obtains access to our servers) to retrieve your <i>original plaintext password</i> with enough effort. These credentials are never sent anywhere outside of our
					servers once you give them to us.</li>
				<li><b>Automatically fill in your asynchronous attendance forms in your name: </b>I mean, you're probably aware of this given that it's the purpose of <code>nffu</code> but 
					I'm putting it here in case you somehow didn't know what you were signing up for?</li>
				<li><b>Store other book-keeping information:</b> In order to provide the service, we store your username, password (and potentially your Discord ID) in addition to various
					internal information. These passwords (the one you just entered on the sign-up page) are stored securely with PBKDF2-HMAC with SHA512 in a way that is infeasible to
					obtain, even with direct access to the database. This information is never sent anywhere outside of our servers once you give it to us, except when necessary to provide
					the service (i.e. we send your username back to you when you are using the web-ui) </li>
				<li><b>Ocassionally view timetable/form-filling statistics:</b> In order to maintain the service, we may occasionally look at the log files generated by the form-filling job
					to ensure it is running correctly. These log files contain screenshots of the filled in forms (which are the same ones available in the web-ui) in addition to information
					about your timetable.</li>
			</ul>
			<p>If you change your mind after accepting these terms and no longer want us to store your information, you can delete your account through the web-ui.</p>
			<p>
				THIS SERVICE IS PROVIDED "AS IS" AND THE AUTHORS AND OPERATORS DISCLAIM ALL WARRANTIES
				WITH REGARD TO THIS SERVICE INCLUDING ALL IMPLIED WARRANTIES OF
				MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHORS OR OPERATORS BE LIABLE FOR
				ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
				WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
				ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
				OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE SERVICE.
			</p>
			<p>If you wish to further verify our claims, <code>nffu</code>'s source code is available by clicking <a href="https://github.com/tylertian123/nffu" target="_blank">here</a> for your perusal.</p>
		<hr />
		<Button disabled={sending} variant="success" onClick={sign_eula}>Agree</Button>{' '}
		<Button disabled={sending} variant="danger"  onClick={delete_account} className="float-right">Disagree and Delete Account</Button>
		{sending ? (<>
			<hr />
			<Row className="justify-content-center"><Spinner animation="border" variant="primary" /></Row>
		</>) : null}
	</>
}

export { EulaSigningCeremony };
